### ISSUE TITLE
Cannot locate 

### ISSUE THREAD

**Issue by hawkinsw** [stanleybak/AeroBenchVVPython#3]
In v1 there are checks in the pass/fail automaton that guarantee airspeed, alpha, beta, etc are within proper limits:
```
        @abc.abstractmethod
        def advance(self, t, x_f16, autopilot_state, xd, u, Nz, ps, Ny_r):
        '''advance the automaton state based on the current aircraft state'''

        airspeed = x_f16[0]
        self.check('airspeed', t, airspeed, self.flightLimits.vMin, self.flightLimits.vMax)

        alpha = rad2deg(x_f16[1])
        self.check('alpha', t, alpha, self.flightLimits.alphaMinDeg, self.flightLimits.alphaMaxDeg)

        beta = rad2deg(x_f16[2])
        self.check('beta', t, beta, -self.flightLimits.betaMaxDeg, self.flightLimits.betaMaxDeg)

        self.check('Nz', t, Nz, self.flightLimits.NzMin, self.flightLimits.NzMax)

        altitude = x_f16[11]
        self.check('altitude', t, altitude, self.flightLimits.altitudeMin, self.flightLimits.altitudeMax)
```

However, in v2, I can find only that `Nz` is checked
```
        def get_checked_u_ref(self, t, x_f16):
        '''
        for the current discrete state, get the reference inputs signals and check them against ctrl limits
        '''

        rv = np.array(self.get_u_ref(t, x_f16), dtype=float)

        assert rv.size % 4 == 0, "get_u_ref should return Nz, ps, Ny_r, throttle for each aircraft"

        for i in range(rv.size //4):
            Nz, _ps, _Ny_r, _throttle = rv[4*i:4*(i+1)]

            l, u = self.llc.ctrlLimits.NzMin, self.llc.ctrlLimits.NzMax
            assert l <= Nz <= u, f"autopilot commanded invalid Nz ({Nz}). Not in range [{l}, {u}]"

        return rv

```

I am obviously missing something, but would really appreciate you pointing out my misunderstanding. It seems like in v2 there is no explicit pass/fail automaton and it's all integrated. That would seem to render the different `check_*.py` files moot. Am I correct in saying that?

Thanks for your help!
Will

**Comment by stanleybak** [comment]
Yes that's right. The `check_*` files should be deleted in v2 (are they not?). The way to add this back in if you want would be to have post processing checks for the limits in your code (by examining `res['states']` where `res` is the value returned by `run_f16_sim`).

In the `acasxu` branch that I'll merge eventually, there are a few checks done in `run_f16_sim` that attempt to make sure the behavior stays within the model limits, but those are not intended as safety property checks: https://github.com/stanleybak/AeroBenchVVPython/blob/acasxu/code/aerobench/run_f16_sim.py#L247

**Comment by hawkinsw** [comment]
Sorry to imply that those `check_*` files were still in v2 of the code -- they are not. I simply went back to v1 to find them since you reference them in the cited paper. Thank you for the workaround. I think a script to run those tests will make this V&V benchmark more useful and I will probably end up writing such a tool and will give it back to you, if you are interested. Just let me know.

As a follow-up question, when you refer to the `acasxu` branch, what code is in there and what is the goal of that branch? Does that branch contain code for another/different autopilot implementation?

Thanks again for all the work on this!

**Comment by hawkinsw** [comment]
I just googled and realize that the acas may be the air collision avoidance system? If that's true, pardon me for not googling first.

**Comment by stanleybak** [comment]
yes it's basically another example autopilot that uses neural networks for collision avoidance. But to implement it I added support for other generic things like multi-aircraft simulation and better plotting capabilities and some restructuring of how simulations are performed so you can pause / resume a simulation if needed.

**Comment by stanleybak** [comment]
Sure if you want to add a file that recreates the scenarios from the paper, I think that would be useful.

**Comment by hawkinsw** [comment]
Thank you for the replies -- they are incredibly helpful! I am looking forward to seeing all the stuff from the `acasxu` branch in master. In the meantime, I will play with it on that branch. Thanks again for all your great work on this code. I am closing this issue.
