### ISSUE TITLE
Running the Simulation with Keyboard Controls

### ISSUE THREAD

**Issue by abdulkadrtr** [stanleybak/AeroBenchVVPython#6]
Hello, I want to use this simulation to set up an RL environment in Python. In short, I need to start the simulation and be able to control the aircraft with the keyboard. This way, I can easily set up the RL environment. Can you help me with how to do this?

**Comment by stanleybak** [comment]
Sounds like a neat project. I think you might be able to use pygame for keyboard input, not sure. I don't think you really need a keyboard to do RL, though, right? I would look at how some of the autopilots interface with the simulation to see what inputs are needed at each step... maybe design your own autopilot first.

For example, here's a simple one you can run / modify: [link](https://github.com/stanleybak/AeroBenchVVPython/blob/afa9f0a062054bd8857b84c434f6288d05f30292/code/aerobench/examples/straight_and_level/run.py#L15)

**Comment by abdulkadrtr** [comment]
Thank you. Actually, I mentioned it that way to make changes to code like keyboard control. That way, it would be easier to understand the code structure. Good luck with your work.
